language: python

python:
  - "2.7"

env:
  - DJANGO=1.6.4
  - DJANGO=1.9

# command to install dependencies
install:
  - pip install git+https://github.com/FOSSEE/online_test.git#egg=yaksh-0.1
  - pip install -q Django==$DJANGO --use-mirrors

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y scilab

# command to run tests
script:
  - python manage.py test yaksh