language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO=1.8.13
  - DJANGO=1.9.5

# command to install dependencies
install:
  - if [[$TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -r requirements/requirements-py2.txt; fi
  - if [[$TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install -r requirements/requirements-py3.txt; fi
  - pip install -q Django==$DJANGO

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y scilab
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - python manage.py test -v 2 yaksh
  - python manage.py test -v 2 yaksh.live_server_tests
