language: python

python:
  - "2.7"

env:
  - DJANGO=1.8.13
  - DJANGO=1.9.5

# command to install dependencies
install:
  - pip install git+https://github.com/FOSSEE/online_test.git#egg=yaksh-0.1
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q pytz==2016.4
  - pip install -q python-social-auth==0.2.19

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y scilab

# command to run tests
script:
  - python manage.py test yaksh
